// pages/Landing.tsx
import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { FileText, ShieldCheck, Zap, ArrowRight, Landmark } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import { Navbar } from '../components/Navbar';

const Landing: React.FC = () => {
  const navigate = useNavigate();
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Navbar />

      {/* Hero */}
      <main className="flex-grow flex flex-col">
        <div className="container mx-auto px-6 py-16 lg:py-24 flex flex-col lg:flex-row items-center">
          <div className="lg:w-1/2 space-y-8 z-10">
            <div className="inline-block px-4 py-1 bg-[#D4AF37]/20 border border-[#D4AF37] rounded-full">
              <span className="text-[#B08D26] font-bold text-xs tracking-[0.2em] uppercase">{t('landing.hero_badge')}</span>
            </div>
            <h1 className="text-5xl lg:text-7xl font-bold text-[#1E293B] leading-tight brand-font">
              {t('landing.title_start')} <br />
              <span className="text-[#00904E]">{t('landing.title_end')}</span>
            </h1>
            <p className="text-xl text-[#64748B] max-w-lg leading-relaxed">
              {t('landing.subtitle')}
            </p>
            <div className="flex space-x-4">
              <Link to="/register" className="bg-[#00904E] text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-[#00703C] transition-all hover:scale-105 flex items-center inline-flex shadow-xl border-b-4 border-[#006030]">
                {t('landing.cta_create')} <ArrowRight className="ml-2 w-5 h-5" />
              </Link>
            </div>
            <div className="flex items-center space-x-6 pt-4 text-sm text-[#64748B]">
              <div className="flex items-center"><ShieldCheck className="w-5 h-5 mr-2 text-[#D4AF37]" /> {t('landing.secure')}</div>
              <div className="flex items-center"><Zap className="w-5 h-5 mr-2 text-[#D4AF37]" /> {t('landing.fast')}</div>
              <div className="flex items-center"><FileText className="w-5 h-5 mr-2 text-[#D4AF37]" /> {t('landing.compatible')}</div>
            </div>
          </div>
          
          <div className="lg:w-1/2 mt-12 lg:mt-0 relative">
            {/* Decorative Flag Elements */}
            <div className="absolute top-0 right-0 w-96 h-96 bg-[#00904E] rounded-full mix-blend-multiply filter blur-3xl opacity-10 animate-blob"></div>
            <div className="absolute top-0 right-40 w-96 h-96 bg-[#D4AF37] rounded-full mix-blend-multiply filter blur-3xl opacity-10 animate-blob animation-delay-2000"></div>
            
            <div className="relative bg-white border border-[#E2E8F0] p-8 rounded-2xl shadow-2xl transform rotate-2 hover:rotate-0 transition-transform duration-500">
              <div className="space-y-6">
                 {/* Fake UI Representation */}
                 <div className="flex items-center justify-between border-b border-gray-100 pb-4">
                    <div className="flex items-center space-x-3">
                      <div className="w-10 h-10 bg-[#00904E] rounded-lg flex items-center justify-center text-white font-bold">VD</div>
                      <div>
                        <div className="h-3 bg-gray-200 rounded w-24 mb-1"></div>
                        <div className="h-2 bg-gray-100 rounded w-16"></div>
                      </div>
                    </div>
                    <div className="text-[#00904E] font-bold">VaudTax</div>
                 </div>
                 <div className="space-y-3">
                    <div className="h-12 bg-[#F8FAFC] rounded border border-gray-100 w-full flex items-center px-4">
                      <div className="h-4 bg-gray-200 rounded w-1/2"></div>
                    </div>
                    <div className="h-12 bg-[#F8FAFC] rounded border border-gray-100 w-full flex items-center px-4 justify-between">
                       <div className="h-4 bg-gray-200 rounded w-1/3"></div>
                       <div className="h-4 bg-[#D4AF37]/40 rounded w-1/4"></div>
                    </div>
                 </div>
                 <div className="pt-4 flex justify-end">
                   <div className="h-10 bg-[#00904E] rounded w-1/3 shadow-lg"></div>
                 </div>
              </div>
            </div>
          </div>
        </div>
        
        {/* Bottom Green Strip representing the flag */}
        <div className="bg-[#00904E] w-full h-32 mt-auto relative overflow-hidden">
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10"></div>
          <div className="container mx-auto px-6 h-full flex items-center justify-between text-white/80">
             <span className="brand-font italic text-2xl text-white/20">{t('brand.motto')}</span>
             <span className="text-sm">{t('landing.footer')}</span>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Landing;

// vaudtax/frontend/src/pages/Landing.vue
<template>
  <div class="d-flex flex-column min-vh-100 bg-white">
    <Navbar />

    <main class="flex-grow-1 d-flex flex-column">
      <!-- Hero -->
      <div class="container py-5">
        <div class="row align-items-center g-5">
          <!-- Left -->
          <div class="col-lg-6">
            <span class="badge bg-gold-soft text-gold-dark border border-warning-subtle mb-3 px-3 py-2" style="letter-spacing:.15em;font-size:.7rem;text-transform:uppercase;font-weight:700">
              {{ t('landing.hero_badge') }}
            </span>
            <h1 class="display-4 fw-bold text-slate lh-sm mb-4">
              {{ t('landing.title_start') }}<br>
              <span class="text-brand">{{ t('landing.title_end') }}</span>
            </h1>
            <p class="fs-5 text-muted-brand mb-4">{{ t('landing.subtitle') }}</p>
            <div class="d-flex gap-3 mb-4">
              <router-link to="/register" class="btn btn-brand btn-lg d-inline-flex align-items-center gap-2 px-4">
                {{ t('landing.cta_create') }}
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/>
                </svg>
              </router-link>
            </div>
            <div class="d-flex gap-4 text-muted-brand" style="font-size:.875rem">
              <div class="d-flex align-items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" class="text-gold" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><polyline points="9 12 11 14 15 10"/>
                </svg>
                {{ t('landing.secure') }}
              </div>
              <div class="d-flex align-items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" class="text-gold" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
                </svg>
                {{ t('landing.fast') }}
              </div>
              <div class="d-flex align-items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" class="text-gold" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/>
                </svg>
                {{ t('landing.compatible') }}
              </div>
            </div>
          </div>

          <!-- Right – decorative card -->
          <div class="col-lg-6 d-flex justify-content-center">
            <div class="card card-brand shadow p-4" style="max-width:400px;width:100%;transform:rotate(2deg);transition:transform .4s" onmouseenter="this.style.transform='rotate(0deg)'" onmouseleave="this.style.transform='rotate(2deg)'">
              <div class="d-flex align-items-center justify-content-between border-bottom pb-3 mb-3">
                <div class="d-flex align-items-center gap-3">
                  <div class="bg-brand rounded-2 d-flex align-items-center justify-content-center text-white fw-bold" style="width:40px;height:40px">VD</div>
                  <div>
                    <div class="bg-secondary bg-opacity-25 rounded" style="height:10px;width:80px;margin-bottom:4px"></div>
                    <div class="bg-secondary bg-opacity-10 rounded" style="height:8px;width:55px"></div>
                  </div>
                </div>
                <span class="text-brand fw-bold">VaudTax</span>
              </div>
              <div class="d-flex flex-column gap-2">
                <div class="bg-page rounded border border-subtle d-flex align-items-center px-3" style="height:48px">
                  <div class="bg-secondary bg-opacity-25 rounded w-50" style="height:12px"></div>
                </div>
                <div class="bg-page rounded border border-subtle d-flex align-items-center justify-content-between px-3" style="height:48px">
                  <div class="bg-secondary bg-opacity-25 rounded w-25" style="height:12px"></div>
                  <div class="bg-gold-soft rounded" style="height:12px;width:25%"></div>
                </div>
              </div>
              <div class="d-flex justify-content-end mt-3">
                <div class="bg-brand rounded" style="height:36px;width:33%"></div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Bottom strip -->
      <div class="bg-brand mt-auto py-4">
        <div class="container d-flex align-items-center justify-content-between text-white">
          <span class="fst-italic fs-4 opacity-25">{{ t('brand.motto') }}</span>
          <small class="opacity-75">{{ t('landing.footer') }}</small>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup>
import Navbar from '../components/Navbar.vue'
import { useLanguageStore } from '../stores/language'

const languageStore = useLanguageStore()
const t = (key) => languageStore.t(key)
</script>
