// vaudtax/frontend/src/pages/Dashboard.vue
<template>
  <div class="min-vh-100 bg-page pb-5">
    <Navbar />

    <main class="container py-5">
      <div class="d-flex justify-content-between align-items-center mb-5">
        <h1 class="fw-bold text-slate mb-0">{{ t('dashboard.title') }}</h1>
        <router-link to="/declarations/new" class="btn btn-brand d-flex align-items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/>
          </svg>
          {{ t('dashboard.new_btn') }}
        </router-link>
      </div>

      <!-- Empty state -->
      <div class="card card-brand border-dashed text-center p-5">
        <div class="d-flex flex-column align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" class="text-light-brand mb-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>
          </svg>
          <h5 class="fw-semibold text-slate">{{ t('dashboard.empty_title') }}</h5>
          <p class="text-muted-brand small mb-3">{{ t('dashboard.empty_desc') }}</p>
          <router-link to="/declarations/new" class="text-brand fw-bold small text-decoration-none">
            {{ t('dashboard.start_now') }}
          </router-link>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup>
import Navbar from '../components/Navbar.vue'
import { useLanguageStore } from '../stores/language'

const languageStore = useLanguageStore()
const t = (key) => languageStore.t(key)
</script>

<style scoped>
.border-dashed { border: 2px dashed var(--brand-border) !important; }
</style>

// pages/Dashboard.tsx
import React from 'react';
import { Navbar } from '../components/Navbar';
import { PlusCircle, FileText, Clock, ChevronRight } from 'lucide-react';
import { useNavigate, Link } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';

const Dashboard: React.FC = () => {
  const navigate = useNavigate();
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-[#F8FAFC] pb-12">
      <Navbar />
      
      <main className="container mx-auto px-6 py-10">
        <div className="flex justify-between items-center mb-10">
          <h1 className="text-3xl font-bold text-[#1E293B] brand-font">{t('dashboard.title')}</h1>
          <Link 
            to="/declaration"
            className="bg-[#00904E] text-white px-6 py-3 rounded-xl font-bold flex items-center hover:bg-[#00703C] shadow-md hover:shadow-lg transition-all"
          >
            <PlusCircle className="w-5 h-5 mr-2" />
            {t('dashboard.new_btn')}
          </Link>
        </div>

        {/* Empty State / List */}
        <div className="grid gap-6">
          {/* Mock Existing Declaration */}
          <div className="bg-white border border-[#E2E8F0] rounded-xl p-6 hover:border-[#00904E] hover:shadow-md transition-all cursor-pointer group">
            <div className="flex justify-between items-center">
              <div className="flex items-center space-x-4">
                <div className="bg-[#F0FDF4] p-3 rounded-lg text-[#00904E]">
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-[#1E293B] group-hover:text-[#00904E] transition-colors">Déclaration 2023</h3>
                  <p className="text-sm text-[#64748B]">{t('dashboard.modified')} 15.03.2024</p>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <span className="bg-[#00904E]/10 text-[#00904E] px-3 py-1 rounded-full text-xs font-bold border border-[#00904E]/20">{t('dashboard.status_finished')}</span>
                <ChevronRight className="w-5 h-5 text-[#94A3B8]" />
              </div>
            </div>
          </div>

          <div className="bg-[#F8FAFC] border-2 border-dashed border-[#CBD5E1] rounded-xl p-8 flex flex-col items-center justify-center text-center">
            <Clock className="w-12 h-12 text-[#94A3B8] mb-4" />
            <h3 className="text-[#1E293B] font-medium brand-font text-lg">{t('dashboard.empty_title')}</h3>
            <p className="text-[#64748B] text-sm mt-1">{t('dashboard.empty_desc')}</p>
            <Link 
              to="/declaration"
              className="mt-4 text-[#00904E] text-sm font-bold hover:underline"
            >
              {t('dashboard.start_now')}
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Dashboard;
